-- AI赋能全景图：版本快照迁移
-- 在 Supabase SQL Editor 中完整执行一次。

create table if not exists public.ai_panorama_versions (
  id bigint generated by default as identity primary key,
  data jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists ai_panorama_versions_created_at_idx
  on public.ai_panorama_versions (created_at desc);

alter table public.ai_panorama_versions enable row level security;
revoke all on table public.ai_panorama_versions from anon, authenticated;

create or replace function public.save_ai_panorama_version(p_data jsonb)
returns table(version_id bigint, updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  saved_at timestamptz := now();
  saved_version_id bigint;
begin
  insert into public.ai_panorama_data (id, data, updated_at)
  values ('default', p_data, saved_at)
  on conflict (id) do update
    set data = excluded.data,
        updated_at = excluded.updated_at;

  insert into public.ai_panorama_versions (data, created_at)
  values (p_data, saved_at)
  returning id into saved_version_id;

  return query select saved_version_id, saved_at;
end;
$$;

revoke all on function public.save_ai_panorama_version(jsonb) from public;
grant execute on function public.save_ai_panorama_version(jsonb) to service_role;
